In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [14]:
iris = load_iris()

X = iris.data
y = iris.target

print("Feature names:", iris.feature_names)
print("Target names:", iris.target_names)
print("Dataset shape:", X.shape)

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']
Dataset shape: (150, 4)


In [15]:
# Select Setosa (0) and Versicolor (1)
mask = y < 2

X_binary = X[mask]
y_binary = y[mask]

print("Binary dataset shape:", X_binary.shape)
print("Classes:", np.unique(y_binary))

Binary dataset shape: (100, 4)
Classes: [0 1]


In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    X_binary,
    y_binary,
    test_size=0.2,
    random_state=42,
    stratify=y_binary
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

Training samples: 80
Testing samples: 20


In [17]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [18]:
perceptron = Perceptron(
    max_iter=1000,
    eta0=0.1,
    random_state=42
)

perceptron.fit(X_train, y_train)

print("Perceptron model trained successfully.")

Perceptron model trained successfully.


In [19]:
y_pred = perceptron.predict(X_test)

print("Predicted values:")
print(y_pred)

print("\nActual values:")
print(y_test)

Predicted values:
[1 1 1 1 0 0 0 1 0 0 0 1 0 0 0 1 1 0 1 1]

Actual values:
[1 1 1 1 0 0 0 1 0 0 0 1 0 0 0 1 1 0 1 1]


In [20]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Accuracy (%):", accuracy * 100)

Accuracy: 1.0
Accuracy (%): 100.0


In [21]:
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[10  0]
 [ 0 10]]


In [22]:
print(classification_report(
    y_test,
    y_pred,
    target_names=["Setosa", "Versicolor"]
))

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        10
  Versicolor       1.00      1.00      1.00        10

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [23]:
new_flower = [[5.1, 3.5, 1.4, 0.2]]

# Scale the input
new_flower_scaled = scaler.transform(new_flower)

prediction = perceptron.predict(new_flower_scaled)

if prediction[0] == 0:
    print("Predicted class: Setosa")
else:
    print("Predicted class: Versicolor")

Predicted class: Setosa
